/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    AssetClassAndApy,
    AssetClassAndApyFromJSON,
    AssetClassAndApyToJSON,
} from '../models';

/**
 * 
 */
export class AssetClassesApi extends runtime.BaseAPI {

    /**
     * Gets list of asset classes
     */
    async getAssetClassesRaw(): Promise<runtime.ApiResponse<Array<AssetClassAndApy>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/asset_classes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssetClassAndApyFromJSON));
    }

    /**
     * Gets list of asset classes
     */
    async getAssetClasses(): Promise<Array<AssetClassAndApy>> {
        const response = await this.getAssetClassesRaw();
        return await response.value();
    }

}
