/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    LeaderboardResponse,
    LeaderboardResponseFromJSON,
    LeaderboardResponseToJSON,
} from '../models';

export interface GetLeaderboardRequest {
    type: GetLeaderboardTypeEnum;
}

/**
 * 
 */
export class LeaderboardApi extends runtime.BaseAPI {

    /**
     * Get a leaderboard
     */
    async getLeaderboardRaw(requestParameters: GetLeaderboardRequest): Promise<runtime.ApiResponse<LeaderboardResponse>> {
        if (requestParameters.type === null || requestParameters.type === undefined) {
            throw new runtime.RequiredError('type','Required parameter requestParameters.type was null or undefined when calling getLeaderboard.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboard/{type}`.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters.type))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardResponseFromJSON(jsonValue));
    }

    /**
     * Get a leaderboard
     */
    async getLeaderboard(requestParameters: GetLeaderboardRequest): Promise<LeaderboardResponse> {
        const response = await this.getLeaderboardRaw(requestParameters);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetLeaderboardTypeEnum {
    Savings = 'savings',
    Spending = 'spending',
    Income = 'income'
}
