/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    Plan,
    PlanFromJSON,
    PlanToJSON,
    PlanNewPayload,
    PlanNewPayloadFromJSON,
    PlanNewPayloadToJSON,
    PlanResponse,
    PlanResponseFromJSON,
    PlanResponseToJSON,
} from '../models';

export interface DeletePlanRequest {
    id: string;
}

export interface GetPlanWithDaysRequest {
    days: number;
}

export interface NewPlanRequest {
    planNewPayload: PlanNewPayload;
}

export interface NewPlanWithDaysRequest {
    days: number;
    planNewPayload: PlanNewPayload;
}

/**
 * 
 */
export class PlanApi extends runtime.BaseAPI {

    /**
     * Delete one specific plan by id
     */
    async deletePlanRaw(requestParameters: DeletePlanRequest): Promise<runtime.ApiResponse<Plan>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deletePlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanFromJSON(jsonValue));
    }

    /**
     * Delete one specific plan by id
     */
    async deletePlan(requestParameters: DeletePlanRequest): Promise<Plan> {
        const response = await this.deletePlanRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get one specific plan and generate timeseries for 365 days
     */
    async getPlanRaw(): Promise<runtime.ApiResponse<PlanResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * Get one specific plan and generate timeseries for 365 days
     */
    async getPlan(): Promise<PlanResponse> {
        const response = await this.getPlanRaw();
        return await response.value();
    }

    /**
     * Get one specific plan and generate timeseries for specified number of days
     */
    async getPlanWithDaysRaw(requestParameters: GetPlanWithDaysRequest): Promise<runtime.ApiResponse<PlanResponse>> {
        if (requestParameters.days === null || requestParameters.days === undefined) {
            throw new runtime.RequiredError('days','Required parameter requestParameters.days was null or undefined when calling getPlanWithDays.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan/{days}`.replace(`{${"days"}}`, encodeURIComponent(String(requestParameters.days))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * Get one specific plan and generate timeseries for specified number of days
     */
    async getPlanWithDays(requestParameters: GetPlanWithDaysRequest): Promise<PlanResponse> {
        const response = await this.getPlanWithDaysRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get all of a user\'s plans
     */
    async getPlansRaw(): Promise<runtime.ApiResponse<Array<Plan>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plans`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlanFromJSON));
    }

    /**
     * Get all of a user\'s plans
     */
    async getPlans(): Promise<Array<Plan>> {
        const response = await this.getPlansRaw();
        return await response.value();
    }

    /**
     * Creates a new plan for the user and generate timeseries for 365 days
     */
    async newPlanRaw(requestParameters: NewPlanRequest): Promise<runtime.ApiResponse<PlanResponse>> {
        if (requestParameters.planNewPayload === null || requestParameters.planNewPayload === undefined) {
            throw new runtime.RequiredError('planNewPayload','Required parameter requestParameters.planNewPayload was null or undefined when calling newPlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/plan/new`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlanNewPayloadToJSON(requestParameters.planNewPayload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new plan for the user and generate timeseries for 365 days
     */
    async newPlan(requestParameters: NewPlanRequest): Promise<PlanResponse> {
        const response = await this.newPlanRaw(requestParameters);
        return await response.value();
    }

    /**
     * Creates a new plan for the user and generate timeseries for specified number of days
     */
    async newPlanWithDaysRaw(requestParameters: NewPlanWithDaysRequest): Promise<runtime.ApiResponse<PlanResponse>> {
        if (requestParameters.days === null || requestParameters.days === undefined) {
            throw new runtime.RequiredError('days','Required parameter requestParameters.days was null or undefined when calling newPlanWithDays.');
        }

        if (requestParameters.planNewPayload === null || requestParameters.planNewPayload === undefined) {
            throw new runtime.RequiredError('planNewPayload','Required parameter requestParameters.planNewPayload was null or undefined when calling newPlanWithDays.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/plan/new/{days}`.replace(`{${"days"}}`, encodeURIComponent(String(requestParameters.days))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlanNewPayloadToJSON(requestParameters.planNewPayload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new plan for the user and generate timeseries for specified number of days
     */
    async newPlanWithDays(requestParameters: NewPlanWithDaysRequest): Promise<PlanResponse> {
        const response = await this.newPlanWithDaysRaw(requestParameters);
        return await response.value();
    }

}
