/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    Plan,
    PlanFromJSON,
    PlanToJSON,
    PlanNewPayload,
    PlanNewPayloadFromJSON,
    PlanNewPayloadToJSON,
} from '../models';

export interface DeletePlanRequest {
    id: string;
}

export interface GetPlanRequest {
    id: string;
}

export interface NewPlanRequest {
    planNewPayload: PlanNewPayload;
}

export interface UpdatePlanRequest {
    id: string;
}

/**
 * 
 */
export class PlanApi extends runtime.BaseAPI {

    /**
     * Delete one specific plan by id
     */
    async deletePlanRaw(requestParameters: DeletePlanRequest): Promise<runtime.ApiResponse<Plan>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deletePlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanFromJSON(jsonValue));
    }

    /**
     * Delete one specific plan by id
     */
    async deletePlan(requestParameters: DeletePlanRequest): Promise<Plan> {
        const response = await this.deletePlanRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get one specific plan by id
     */
    async getPlanRaw(requestParameters: GetPlanRequest): Promise<runtime.ApiResponse<Plan>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getPlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanFromJSON(jsonValue));
    }

    /**
     * Get one specific plan by id
     */
    async getPlan(requestParameters: GetPlanRequest): Promise<Plan> {
        const response = await this.getPlanRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get all of a user\'s plans
     */
    async getPlansRaw(): Promise<runtime.ApiResponse<Array<Plan>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plans`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlanFromJSON));
    }

    /**
     * Get all of a user\'s plans
     */
    async getPlans(): Promise<Array<Plan>> {
        const response = await this.getPlansRaw();
        return await response.value();
    }

    /**
     * Creates a new plan for the user
     */
    async newPlanRaw(requestParameters: NewPlanRequest): Promise<runtime.ApiResponse<Plan>> {
        if (requestParameters.planNewPayload === null || requestParameters.planNewPayload === undefined) {
            throw new runtime.RequiredError('planNewPayload','Required parameter requestParameters.planNewPayload was null or undefined when calling newPlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/plan/new`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlanNewPayloadToJSON(requestParameters.planNewPayload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanFromJSON(jsonValue));
    }

    /**
     * Creates a new plan for the user
     */
    async newPlan(requestParameters: NewPlanRequest): Promise<Plan> {
        const response = await this.newPlanRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update one specific plan by id
     */
    async updatePlanRaw(requestParameters: UpdatePlanRequest): Promise<runtime.ApiResponse<Plan>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updatePlan.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plan/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PlanFromJSON(jsonValue));
    }

    /**
     * Update one specific plan by id
     */
    async updatePlan(requestParameters: UpdatePlanRequest): Promise<Plan> {
        const response = await this.updatePlanRaw(requestParameters);
        return await response.value();
    }

}
