/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    TimeSeries,
    TimeSeriesFromJSON,
    TimeSeriesToJSON,
} from '../models';

/**
 * 
 */
export class TimeseriesApi extends runtime.BaseAPI {

    /**
     * Get a user\'s projection timeseries
     */
    async getTimeseriesRaw(): Promise<runtime.ApiResponse<TimeSeries>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/timeseries`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesFromJSON(jsonValue));
    }

    /**
     * Get a user\'s projection timeseries
     */
    async getTimeseries(): Promise<TimeSeries> {
        const response = await this.getTimeseriesRaw();
        return await response.value();
    }

}
