/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    ValidateUserPayload,
    ValidateUserPayloadFromJSON,
    ValidateUserPayloadToJSON,
} from '../models';

export interface ValidateUserRequest {
    validateUserPayload: ValidateUserPayload;
}

/**
 * 
 */
export class ValidationApi extends runtime.BaseAPI {

    /**
     * This route lets our clients perform step-by-step signups.
     */
    async validateUserRaw(requestParameters: ValidateUserRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.validateUserPayload === null || requestParameters.validateUserPayload === undefined) {
            throw new runtime.RequiredError('validateUserPayload','Required parameter requestParameters.validateUserPayload was null or undefined when calling validateUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/validate/user`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateUserPayloadToJSON(requestParameters.validateUserPayload),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This route lets our clients perform step-by-step signups.
     */
    async validateUser(requestParameters: ValidateUserRequest): Promise<void> {
        await this.validateUserRaw(requestParameters);
    }

}
