openapi: 3.0.0
info:
  version: 0.0.1
  title: FinchAPI
servers:
  - url: "https://localhost:8888"
paths:
  /api/signup:
    post:
      summary: "Sign up a user"
      operationId: signupUser
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupPayload"
      responses:
        "200":
          description: "User Info"
          headers:
            Set-Cookie:
              description: >
                Contains the session cookies named `sid` and `user_id`.
                Pass this cookie back in subsequent requests.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/login:
    post:
      summary: "Log in a user"
      operationId: loginUser
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginPayload"
      responses:
        "200":
          description: "User Info"
          headers:
            Set-Cookie:
              description: >
                Contains the session cookies named `sid` and `user_id`.
                Pass this cookie back in subsequent requests.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/plaid/link_token:
    post:
      summary: "to request link token for PlaidLink"
      operationId: plaidLink
      tags:
        - plaid
      security:
        - sidCookie: []
          userIdCookie: []
      responses:
        "200":
          description: "Link Token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LinkTokenCreateResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/plaid/public_token_exchange:
    post:
      summary: "For after a user does PlaidLink thru client"
      operationId: plaidLinkAccess
      tags:
        - plaid
      security:
        - sidCookie: []
          userIdCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublicTokenExchangeRequest"
      responses:
        "200":
          description: "Status"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemIdResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  securitySchemes:
    sidCookie:
      type: apiKey
      in: cookie
      name: sid
    userIdCookie:
      type: apiKey
      in: cookie
      name: user_id
  schemas:
    SignupPayload:
      type: object
      required:
        - email
        - password
        - first_name
        - last_name
        - income
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        income:
          type: number
    LoginPayload:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    SignupResponse:
      type: object
      required:
        - email
        - first_name
        - last_name
        - income
      properties:
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        income:
          type: number
    LoginResponse:
      $ref: "#/components/schemas/SignupResponse"
    LinkTokenCreateResponse:
      type: object
      required:
        - link_token
        - expiration
      properties:
        link_token:
          type: string
        expiration:
          type: string
        request_id:
          type: string
    ItemIdResponse:
      type: object
      required:
        - item_id
      properties:
        item_id:
          type: string
          description: "Item ID for newly added account"
    PublicTokenExchangeRequest:
      type: object
      required:
        - public_token
      properties:
        public_token:
          type: string
        client_id:
          type: string
        secret:
          type: string
    ApiError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
