/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Account,
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountError,
    AccountErrorFromJSON,
    AccountErrorFromJSONTyped,
    AccountErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountsResponse
 */
export interface AccountsResponse {
    /**
     * 
     * @type {Array<Account>}
     * @memberof AccountsResponse
     */
    accounts: Array<Account>;
    /**
     * 
     * @type {Array<AccountError>}
     * @memberof AccountsResponse
     */
    errors: Array<AccountError>;
}

export function AccountsResponseFromJSON(json: any): AccountsResponse {
    return AccountsResponseFromJSONTyped(json, false);
}

export function AccountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(AccountFromJSON)),
        'errors': ((json['errors'] as Array<any>).map(AccountErrorFromJSON)),
    };
}

export function AccountsResponseToJSON(value?: AccountsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accounts': ((value.accounts as Array<any>).map(AccountToJSON)),
        'errors': ((value.errors as Array<any>).map(AccountErrorToJSON)),
    };
}


