/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Asset,
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
} from './';

/**
 * 
 * @export
 * @interface AllocationChange
 */
export interface AllocationChange {
    /**
     * 
     * @type {Asset}
     * @memberof AllocationChange
     */
    asset: Asset;
    /**
     * 
     * @type {number}
     * @memberof AllocationChange
     */
    change: number;
}

export function AllocationChangeFromJSON(json: any): AllocationChange {
    return AllocationChangeFromJSONTyped(json, false);
}

export function AllocationChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'asset': AssetFromJSON(json['asset']),
        'change': json['change'],
    };
}

export function AllocationChangeToJSON(value?: AllocationChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset': AssetToJSON(value.asset),
        'change': value.change,
    };
}


