/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Asset,
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
} from './';

/**
 * 
 * @export
 * @interface AllocationProportion
 */
export interface AllocationProportion {
    /**
     * 
     * @type {Asset}
     * @memberof AllocationProportion
     */
    asset: Asset;
    /**
     * 
     * @type {number}
     * @memberof AllocationProportion
     */
    proportion: number;
}

export function AllocationProportionFromJSON(json: any): AllocationProportion {
    return AllocationProportionFromJSONTyped(json, false);
}

export function AllocationProportionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationProportion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'asset': AssetFromJSON(json['asset']),
        'proportion': json['proportion'],
    };
}

export function AllocationProportionToJSON(value?: AllocationProportion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset': AssetToJSON(value.asset),
        'proportion': value.proportion,
    };
}


