/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AllocationChange,
    AllocationChangeFromJSON,
    AllocationChangeFromJSONTyped,
    AllocationChangeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Allocation
 */
export interface Allocation {
    /**
     * 
     * @type {string}
     * @memberof Allocation
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof Allocation
     */
    date: number;
    /**
     * 
     * @type {AllocationChange}
     * @memberof Allocation
     */
    schema: AllocationChange;
}

export function AllocationFromJSON(json: any): Allocation {
    return AllocationFromJSONTyped(json, false);
}

export function AllocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Allocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'date': json['date'],
        'schema': AllocationChangeFromJSON(json['schema']),
    };
}

export function AllocationToJSON(value?: Allocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'date': value.date,
        'schema': AllocationChangeToJSON(value.schema),
    };
}


