/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetToPercentMapping
 */
export interface AssetToPercentMapping {
    /**
     * 
     * @type {number}
     * @memberof AssetToPercentMapping
     */
    percentage: number;
}

export function AssetToPercentMappingFromJSON(json: any): AssetToPercentMapping {
    return AssetToPercentMappingFromJSONTyped(json, false);
}

export function AssetToPercentMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetToPercentMapping {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'percentage': json['percentage'],
    };
}

export function AssetToPercentMappingToJSON(value?: AssetToPercentMapping | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'percentage': value.percentage,
    };
}


