/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetClass,
    AssetClassFromJSON,
    AssetClassFromJSONTyped,
    AssetClassToJSON,
} from './';

/**
 * 
 * @export
 * @interface AssetClassChange
 */
export interface AssetClassChange {
    /**
     * 
     * @type {AssetClass}
     * @memberof AssetClassChange
     */
    _class: AssetClass;
    /**
     * 
     * @type {number}
     * @memberof AssetClassChange
     */
    change: number;
}

export function AssetClassChangeFromJSON(json: any): AssetClassChange {
    return AssetClassChangeFromJSONTyped(json, false);
}

export function AssetClassChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetClassChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_class': AssetClassFromJSON(json['class']),
        'change': json['change'],
    };
}

export function AssetClassChangeToJSON(value?: AssetClassChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class': AssetClassToJSON(value._class),
        'change': value.change,
    };
}


