/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetClass,
    AssetClassFromJSON,
    AssetClassFromJSONTyped,
    AssetClassToJSON,
} from './';

/**
 * 
 * @export
 * @interface AssetClassAndApy
 */
export interface AssetClassAndApy {
    /**
     * 
     * @type {AssetClass}
     * @memberof AssetClassAndApy
     */
    _class: AssetClass;
    /**
     * 
     * @type {number}
     * @memberof AssetClassAndApy
     */
    apy: number;
}

export function AssetClassAndApyFromJSON(json: any): AssetClassAndApy {
    return AssetClassAndApyFromJSONTyped(json, false);
}

export function AssetClassAndApyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetClassAndApy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_class': AssetClassFromJSON(json['class']),
        'apy': json['apy'],
    };
}

export function AssetClassAndApyToJSON(value?: AssetClassAndApy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class': AssetClassToJSON(value._class),
        'apy': value.apy,
    };
}


