/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetClass
 */
export interface AssetClass {
    /**
     * what type of asset it is
     * @type {string}
     * @memberof AssetClass
     */
    typ: AssetClassTypEnum;
    /**
     * extra info, such as symbol name, used in Custom
     * @type {string}
     * @memberof AssetClass
     */
    content?: string;
}

/**
* @export
* @enum {string}
*/
export enum AssetClassTypEnum {
    Cash = 'Cash',
    Equity = 'Equity',
    Etf = 'Etf',
    Fixed = 'Fixed',
    MutualFund = 'MutualFund',
    Other = 'Other',
    Custom = 'Custom'
}

export function AssetClassFromJSON(json: any): AssetClass {
    return AssetClassFromJSONTyped(json, false);
}

export function AssetClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetClass {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typ': json['typ'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function AssetClassToJSON(value?: AssetClass | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'typ': value.typ,
        'content': value.content,
    };
}


