/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BoardType {
    Savings = 'Savings',
    Spending = 'Spending',
    Income = 'Income'
}

export function BoardTypeFromJSON(json: any): BoardType {
    return BoardTypeFromJSONTyped(json, false);
}

export function BoardTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardType {
    return json as BoardType;
}

export function BoardTypeToJSON(value?: BoardType | null): any {
    return value as any;
}

