/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MongoObjectID,
    MongoObjectIDFromJSON,
    MongoObjectIDFromJSONTyped,
    MongoObjectIDToJSON,
    Transform,
    TransformFromJSON,
    TransformFromJSONTyped,
    TransformToJSON,
} from './';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {MongoObjectID}
     * @memberof Event
     */
    _id: MongoObjectID;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    start: number;
    /**
     * 
     * @type {Array<Transform>}
     * @memberof Event
     */
    transforms: Array<Transform>;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': MongoObjectIDFromJSON(json['_id']),
        'name': json['name'],
        'start': json['start'],
        'transforms': ((json['transforms'] as Array<any>).map(TransformFromJSON)),
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': MongoObjectIDToJSON(value._id),
        'name': value.name,
        'start': value.start,
        'transforms': ((value.transforms as Array<any>).map(TransformToJSON)),
    };
}


