/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimePeriod,
    TimePeriodFromJSON,
    TimePeriodFromJSONTyped,
    TimePeriodToJSON,
} from './';

/**
 * 
 * @export
 * @interface GoalNewPayload
 */
export interface GoalNewPayload {
    /**
     * 
     * @type {string}
     * @memberof GoalNewPayload
     */
    name: string;
    /**
     * 
     * @type {TimePeriod}
     * @memberof GoalNewPayload
     */
    period: TimePeriod;
    /**
     * 
     * @type {number}
     * @memberof GoalNewPayload
     */
    threshold: number;
    /**
     * 
     * @type {string}
     * @memberof GoalNewPayload
     */
    goal_side: GoalNewPayloadGoalSideEnum;
}

export function GoalNewPayloadFromJSON(json: any): GoalNewPayload {
    return GoalNewPayloadFromJSONTyped(json, false);
}

export function GoalNewPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalNewPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'period': TimePeriodFromJSON(json['period']),
        'threshold': json['threshold'],
        'goal_side': json['goal_side'],
    };
}

export function GoalNewPayloadToJSON(value?: GoalNewPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'period': TimePeriodToJSON(value.period),
        'threshold': value.threshold,
        'goal_side': value.goal_side,
    };
}

/**
* @export
* @enum {string}
*/
export enum GoalNewPayloadGoalSideEnum {
    Above = 'above',
    Below = 'below'
}


