/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MongoObjectID,
    MongoObjectIDFromJSON,
    MongoObjectIDFromJSONTyped,
    MongoObjectIDToJSON,
    TimePeriod,
    TimePeriodFromJSON,
    TimePeriodFromJSONTyped,
    TimePeriodToJSON,
} from './';

/**
 * 
 * @export
 * @interface Goal
 */
export interface Goal {
    /**
     * 
     * @type {MongoObjectID}
     * @memberof Goal
     */
    _id: MongoObjectID;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    name: string;
    /**
     * 
     * @type {TimePeriod}
     * @memberof Goal
     */
    period: TimePeriod;
    /**
     * 
     * @type {number}
     * @memberof Goal
     */
    threshold: number;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    goal_side: GoalGoalSideEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Goal
     */
    completed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Goal
     */
    feasible?: boolean;
}

export function GoalFromJSON(json: any): Goal {
    return GoalFromJSONTyped(json, false);
}

export function GoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Goal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': MongoObjectIDFromJSON(json['_id']),
        'name': json['name'],
        'period': TimePeriodFromJSON(json['period']),
        'threshold': json['threshold'],
        'goal_side': json['goal_side'],
        'completed': json['completed'],
        'feasible': !exists(json, 'feasible') ? undefined : json['feasible'],
    };
}

export function GoalToJSON(value?: Goal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': MongoObjectIDToJSON(value._id),
        'name': value.name,
        'period': TimePeriodToJSON(value.period),
        'threshold': value.threshold,
        'goal_side': value.goal_side,
        'completed': value.completed,
        'feasible': value.feasible,
    };
}

/**
* @export
* @enum {string}
*/
export enum GoalGoalSideEnum {
    Above = 'above',
    Below = 'below'
}


