/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum GoalMetric {
    Savings = 'Savings',
    Spending = 'Spending',
    Income = 'Income'
}

export function GoalMetricFromJSON(json: any): GoalMetric {
    return GoalMetricFromJSONTyped(json, false);
}

export function GoalMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalMetric {
    return json as GoalMetric;
}

export function GoalMetricToJSON(value?: GoalMetric | null): any {
    return value as any;
}

