/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MongoObjectID,
    MongoObjectIDFromJSON,
    MongoObjectIDFromJSONTyped,
    MongoObjectIDToJSON,
} from './';

/**
 * 
 * @export
 * @interface Insight
 */
export interface Insight {
    /**
     * 
     * @type {MongoObjectID}
     * @memberof Insight
     */
    _id: MongoObjectID;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    insight_type: InsightInsightTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Insight
     */
    dismissed: boolean;
    /**
     * 
     * @type {number}
     * @memberof Insight
     */
    generation_time: number;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    imageURL?: string | null;
}

export function InsightFromJSON(json: any): Insight {
    return InsightFromJSONTyped(json, false);
}

export function InsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): Insight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': MongoObjectIDFromJSON(json['_id']),
        'title': json['title'],
        'description': json['description'],
        'insight_type': json['insight_type'],
        'dismissed': json['dismissed'],
        'generation_time': json['generation_time'],
        'imageURL': !exists(json, 'imageURL') ? undefined : json['imageURL'],
    };
}

export function InsightToJSON(value?: Insight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': MongoObjectIDToJSON(value._id),
        'title': value.title,
        'description': value.description,
        'insight_type': value.insight_type,
        'dismissed': value.dismissed,
        'generation_time': value.generation_time,
        'imageURL': value.imageURL,
    };
}

/**
* @export
* @enum {string}
*/
export enum InsightInsightTypeEnum {
    ProductRecommendation = 'ProductRecommendation',
    Savings = 'Savings',
    Spending = 'Spending',
    Income = 'Income',
    Goal = 'Goal',
    Incomplete = 'Incomplete'
}


