/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Insight
 */
export interface Insight {
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    typ: string;
    /**
     * 
     * @type {boolean}
     * @memberof Insight
     */
    dismissed: boolean;
}

export function InsightFromJSON(json: any): Insight {
    return InsightFromJSONTyped(json, false);
}

export function InsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): Insight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'typ': json['typ'],
        'dismissed': json['dismissed'],
    };
}

export function InsightToJSON(value?: Insight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'logo': value.logo,
        'typ': value.typ,
        'dismissed': value.dismissed,
    };
}


