/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KnownFinancialProduct
 */
export interface KnownFinancialProduct {
    /**
     * 
     * @type {string}
     * @memberof KnownFinancialProduct
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KnownFinancialProduct
     */
    typ: string;
    /**
     * 
     * @type {string}
     * @memberof KnownFinancialProduct
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof KnownFinancialProduct
     */
    product_url: string;
}

export function KnownFinancialProductFromJSON(json: any): KnownFinancialProduct {
    return KnownFinancialProductFromJSONTyped(json, false);
}

export function KnownFinancialProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnownFinancialProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'typ': json['typ'],
        'logo': json['logo'],
        'product_url': json['product_url'],
    };
}

export function KnownFinancialProductToJSON(value?: KnownFinancialProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'typ': value.typ,
        'logo': value.logo,
        'product_url': value.product_url,
    };
}


