/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoObjectID
 */
export interface MongoObjectID {
    /**
     * 
     * @type {string}
     * @memberof MongoObjectID
     */
    $oid: string;
}

export function MongoObjectIDFromJSON(json: any): MongoObjectID {
    return MongoObjectIDFromJSONTyped(json, false);
}

export function MongoObjectIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoObjectID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '$oid': json['$oid'],
    };
}

export function MongoObjectIDToJSON(value?: MongoObjectID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '$oid': value.$oid,
    };
}


