/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidJWT
 */
export interface PlaidJWT {
    /**
     * 
     * @type {string}
     * @memberof PlaidJWT
     */
    alg: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidJWT
     */
    kid: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidJWT
     */
    typ: string;
}

export function PlaidJWTFromJSON(json: any): PlaidJWT {
    return PlaidJWTFromJSONTyped(json, false);
}

export function PlaidJWTFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidJWT {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alg': json['alg'],
        'kid': json['kid'],
        'typ': json['typ'],
    };
}

export function PlaidJWTToJSON(value?: PlaidJWT | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alg': value.alg,
        'kid': value.kid,
        'typ': value.typ,
    };
}


