/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Plan,
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
    TimeSeriesResponse,
    TimeSeriesResponseFromJSON,
    TimeSeriesResponseFromJSONTyped,
    TimeSeriesResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlanResponse
 */
export interface PlanResponse {
    /**
     * 
     * @type {Plan}
     * @memberof PlanResponse
     */
    plan: Plan;
    /**
     * 
     * @type {TimeSeriesResponse}
     * @memberof PlanResponse
     */
    timeseries: TimeSeriesResponse;
}

export function PlanResponseFromJSON(json: any): PlanResponse {
    return PlanResponseFromJSONTyped(json, false);
}

export function PlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plan': PlanFromJSON(json['plan']),
        'timeseries': TimeSeriesResponseFromJSON(json['timeseries']),
    };
}

export function PlanResponseToJSON(value?: PlanResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan': PlanToJSON(value.plan),
        'timeseries': TimeSeriesResponseToJSON(value.timeseries),
    };
}


