/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Allocation,
    AllocationFromJSON,
    AllocationFromJSONTyped,
    AllocationToJSON,
    Event,
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    MongoObjectID,
    MongoObjectIDFromJSON,
    MongoObjectIDFromJSONTyped,
    MongoObjectIDToJSON,
    Recurring,
    RecurringFromJSON,
    RecurringFromJSONTyped,
    RecurringToJSON,
} from './';

/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {MongoObjectID}
     * @memberof Plan
     */
    _id: MongoObjectID;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    name: string;
    /**
     * 
     * @type {Array<Recurring>}
     * @memberof Plan
     */
    recurrings?: Array<Recurring>;
    /**
     * 
     * @type {Array<Allocation>}
     * @memberof Plan
     */
    allocations?: Array<Allocation>;
    /**
     * 
     * @type {Array<Event>}
     * @memberof Plan
     */
    events?: Array<Event>;
}

export function PlanFromJSON(json: any): Plan {
    return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': MongoObjectIDFromJSON(json['_id']),
        'name': json['name'],
        'recurrings': !exists(json, 'recurrings') ? undefined : ((json['recurrings'] as Array<any>).map(RecurringFromJSON)),
        'allocations': !exists(json, 'allocations') ? undefined : ((json['allocations'] as Array<any>).map(AllocationFromJSON)),
        'events': !exists(json, 'events') ? undefined : ((json['events'] as Array<any>).map(EventFromJSON)),
    };
}

export function PlanToJSON(value?: Plan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': MongoObjectIDToJSON(value._id),
        'name': value.name,
        'recurrings': value.recurrings === undefined ? undefined : ((value.recurrings as Array<any>).map(RecurringToJSON)),
        'allocations': value.allocations === undefined ? undefined : ((value.allocations as Array<any>).map(AllocationToJSON)),
        'events': value.events === undefined ? undefined : ((value.events as Array<any>).map(EventToJSON)),
    };
}


