/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicTokenExchangeRequest
 */
export interface PublicTokenExchangeRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicTokenExchangeRequest
     */
    public_token: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenExchangeRequest
     */
    client_id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTokenExchangeRequest
     */
    secret?: string;
}

export function PublicTokenExchangeRequestFromJSON(json: any): PublicTokenExchangeRequest {
    return PublicTokenExchangeRequestFromJSONTyped(json, false);
}

export function PublicTokenExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTokenExchangeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'public_token': json['public_token'],
        'client_id': !exists(json, 'client_id') ? undefined : json['client_id'],
        'secret': !exists(json, 'secret') ? undefined : json['secret'],
    };
}

export function PublicTokenExchangeRequestToJSON(value?: PublicTokenExchangeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'public_token': value.public_token,
        'client_id': value.client_id,
        'secret': value.secret,
    };
}


