/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ranking
 */
export interface Ranking {
    /**
     * 
     * @type {string}
     * @memberof Ranking
     */
    leaderboard_type: string;
    /**
     * 
     * @type {string}
     * @memberof Ranking
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    percentile: number;
}

export function RankingFromJSON(json: any): Ranking {
    return RankingFromJSONTyped(json, false);
}

export function RankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ranking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'leaderboard_type': json['leaderboard_type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'percentile': json['percentile'],
    };
}

export function RankingToJSON(value?: Ranking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'leaderboard_type': value.leaderboard_type,
        'description': value.description,
        'percentile': value.percentile,
    };
}


