/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Location,
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './';

/**
 * 
 * @export
 * @interface SignupPayload
 */
export interface SignupPayload {
    /**
     * 
     * @type {string}
     * @memberof SignupPayload
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupPayload
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupPayload
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof SignupPayload
     */
    last_name: string;
    /**
     * 
     * @type {number}
     * @memberof SignupPayload
     */
    income: number;
    /**
     * 
     * @type {number}
     * @memberof SignupPayload
     */
    net_worth: number;
    /**
     * 
     * @type {Location}
     * @memberof SignupPayload
     */
    location: Location;
    /**
     * 
     * @type {Date}
     * @memberof SignupPayload
     */
    birthday: Date;
}

export function SignupPayloadFromJSON(json: any): SignupPayload {
    return SignupPayloadFromJSONTyped(json, false);
}

export function SignupPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'income': json['income'],
        'net_worth': json['net_worth'],
        'location': LocationFromJSON(json['location']),
        'birthday': (new Date(json['birthday'])),
    };
}

export function SignupPayloadToJSON(value?: SignupPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'first_name': value.first_name,
        'last_name': value.last_name,
        'income': value.income,
        'net_worth': value.net_worth,
        'location': LocationToJSON(value.location),
        'birthday': (value.birthday.toISOString().substr(0,10)),
    };
}


