/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Money,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './';

/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {Money}
     * @memberof Snapshot
     */
    net_worth: Money;
    /**
     * 
     * @type {Money}
     * @memberof Snapshot
     */
    running_savings: Money;
    /**
     * 
     * @type {Money}
     * @memberof Snapshot
     */
    running_spending: Money;
    /**
     * 
     * @type {Money}
     * @memberof Snapshot
     */
    running_income: Money;
    /**
     * 
     * @type {number}
     * @memberof Snapshot
     */
    snapshot_time: number;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'net_worth': MoneyFromJSON(json['net_worth']),
        'running_savings': MoneyFromJSON(json['running_savings']),
        'running_spending': MoneyFromJSON(json['running_spending']),
        'running_income': MoneyFromJSON(json['running_income']),
        'snapshot_time': json['snapshot_time'],
    };
}

export function SnapshotToJSON(value?: Snapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'net_worth': MoneyToJSON(value.net_worth),
        'running_savings': MoneyToJSON(value.running_savings),
        'running_spending': MoneyToJSON(value.running_spending),
        'running_income': MoneyToJSON(value.running_income),
        'snapshot_time': value.snapshot_time,
    };
}


