/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Daily values starting on some day.
 * @export
 * @interface TimeSeries
 */
export interface TimeSeries {
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    start_day: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof TimeSeries
     */
    series: Array<number>;
}

export function TimeSeriesFromJSON(json: any): TimeSeries {
    return TimeSeriesFromJSONTyped(json, false);
}

export function TimeSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start_day': json['start_day'],
        'series': json['series'],
    };
}

export function TimeSeriesToJSON(value?: TimeSeries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_day': value.start_day,
        'series': value.series,
    };
}


