/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimeSeriesEntry,
    TimeSeriesEntryFromJSON,
    TimeSeriesEntryFromJSONTyped,
    TimeSeriesEntryToJSON,
} from './';

/**
 * Today's date, daily values of user's net worth
 * @export
 * @interface TimeSeriesResponse
 */
export interface TimeSeriesResponse {
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesResponse
     */
    start: number;
    /**
     * 
     * @type {Array<TimeSeriesEntry>}
     * @memberof TimeSeriesResponse
     */
    series: Array<TimeSeriesEntry>;
}

export function TimeSeriesResponseFromJSON(json: any): TimeSeriesResponse {
    return TimeSeriesResponseFromJSONTyped(json, false);
}

export function TimeSeriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'series': ((json['series'] as Array<any>).map(TimeSeriesEntryFromJSON)),
    };
}

export function TimeSeriesResponseToJSON(value?: TimeSeriesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'series': ((value.series as Array<any>).map(TimeSeriesEntryToJSON)),
    };
}


