/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimePeriod
 */
export interface TimePeriod {
    /**
     * 
     * @type {number}
     * @memberof TimePeriod
     */
    start: number;
    /**
     * 
     * @type {number}
     * @memberof TimePeriod
     */
    end: number;
}

export function TimePeriodFromJSON(json: any): TimePeriod {
    return TimePeriodFromJSONTyped(json, false);
}

export function TimePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimePeriod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function TimePeriodToJSON(value?: TimePeriod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'end': value.end,
    };
}


