/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetChange,
    AssetChangeFromJSON,
    AssetChangeFromJSONTyped,
    AssetChangeToJSON,
    TimeInterval,
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './';

/**
 * 
 * @export
 * @interface Transform
 */
export interface Transform {
    /**
     * 
     * @type {TimeInterval}
     * @memberof Transform
     */
    trigger: TimeInterval;
    /**
     * 
     * @type {Array<AssetChange>}
     * @memberof Transform
     */
    changes: Array<AssetChange>;
}

export function TransformFromJSON(json: any): Transform {
    return TransformFromJSONTyped(json, false);
}

export function TransformFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transform {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trigger': TimeIntervalFromJSON(json['trigger']),
        'changes': ((json['changes'] as Array<any>).map(AssetChangeFromJSON)),
    };
}

export function TransformToJSON(value?: Transform | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trigger': TimeIntervalToJSON(value.trigger),
        'changes': ((value.changes as Array<any>).map(AssetChangeToJSON)),
    };
}


