/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLocation
 */
export interface UserLocation {
    /**
     * 
     * @type {number}
     * @memberof UserLocation
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof UserLocation
     */
    lon: number;
}

export function UserLocationFromJSON(json: any): UserLocation {
    return UserLocationFromJSONTyped(json, false);
}

export function UserLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lon': json['lon'],
    };
}

export function UserLocationToJSON(value?: UserLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lat': value.lat,
        'lon': value.lon,
    };
}


