/* tslint:disable */
/* eslint-disable */
/**
 * FinchAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateUserPayload
 */
export interface ValidateUserPayload {
    /**
     * 
     * @type {string}
     * @memberof ValidateUserPayload
     */
    field: ValidateUserPayloadFieldEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidateUserPayload
     */
    content: string;
}

export function ValidateUserPayloadFromJSON(json: any): ValidateUserPayload {
    return ValidateUserPayloadFromJSONTyped(json, false);
}

export function ValidateUserPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateUserPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'content': json['content'],
    };
}

export function ValidateUserPayloadToJSON(value?: ValidateUserPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'content': value.content,
    };
}

/**
* @export
* @enum {string}
*/
export enum ValidateUserPayloadFieldEnum {
    Email = 'Email',
    Password = 'Password',
    Birthday = 'Birthday'
}


