on: [workflow_dispatch]

name: Deploy API to Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push API"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$API_CONTAINER:latest --build-arg bin=api -f Dockerfile.rust.prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$API_CONTAINER:latest
        working-directory: server
        env:
          API_CONTAINER: pfp_pfp_server
