on: [workflow_dispatch]

name: Deploy Client to Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push Client"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER_NAME:latest -f Dockerfile-prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER_NAME:latest
        working-directory: client
        env:
          CONTAINER_NAME: pfp_pfp_client
