name: Jest Tests

on:
  pull_request:
    branches: [master]
    paths:
      - "./client/*"

env:
  working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        with:
          path: "${{env.working-directory}}"
        id: package-node-version

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{steps.package-version.outputs.version}}

      - run: npm install
        working-directory: ${{env.working-directory}}

      - run: npm run test
        working-directory: ${{env.working-directory}}
