on: [push, workflow_dispatch]

name: Build and Push Images to ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push Client"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER_NAME:${{ github.sha }} -f Dockerfile-prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER_NAME:${{ github.sha }}
        working-directory: client
        env:
          CONTAINER_NAME: pfp_pfp_client

      - name: "Build and push API Server and Insights Service"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$API_CONTAINER:${{ github.sha }} --build-arg bin=api -f Dockerfile.rust.prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$API_CONTAINER:${{ github.sha }}

          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$SRV_INSIGHTS_CONTAINER:${{ github.sha }} --build-arg bin=service_insights -f Dockerfile.rust.prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$SRV_INSIGHTS_CONTAINER:${{ github.sha }}
        working-directory: server
        env:
          API_CONTAINER: pfp_pfp_server
          SRV_INSIGHTS_CONTAINER: pfp_pfp_insights
