on: [push, workflow_dispatch]

name: Validate OpenAPI spec

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@main

      - name: "Validate OpenAPI"
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            postman/api.yaml
